"""
Django settings for sunshine portal

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/

This settings file is suitable for DEVELOPMENT only.
Do not use in production.
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'secret-key-goes-here'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'sunshine.apps.SunshinePortalConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sunshinesite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'sunshine.context_processors.setup_sunshine_request'
            ],
        },
    },
]

WSGI_APPLICATION = 'sunshinesite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'upload', 'sunshine2.sqlite3.db')
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Singapore'
USE_I18N = True
USE_L10N = True
USE_TZ = True
TIME_ZONE_DST = False


# ------------------------------------------------------------------------------
# Sunshine settings
# ------------------------------------------------------------------------------
LOGIN_URL = '/admin/login'
SUNSHINE_HOME = '/sunshine/home'
SUNSHINE_ADMIN_GROUPS = ["dev"]
SUNSHINE_ENV = 'DEV'  # DEV/UAT/PROD
SUNSHINE_COPYRIGHT = "Sunshine Portal for Django, copyright &copy; <a href='https://github.com/letuananh/sunshine'>Le Tuan Anh</a> 2013"
SUNSHINE_DEFAULT_TITLE = 'Sunshine Portal'
# SUNSHINE_ADMIN_LOGO = ''  # to customize the logo in Admin site
SUNSHINE_BRAND = 'Sunshine Portal<sup>2</sup>'  # frontend site name
if SUNSHINE_ENV == 'DEV':
    ADMIN_SITE_INDEX_TITLE = 'Development instance of Sunshine Portal running locally. It is safe to change things here.'
elif SUNSHINE_ENV == 'UAT':
    ADMIN_SITE_INDEX_TITLE = 'UAT instance of Sunshine Portal. It is safe to play around with things here.'
else:
    ADMIN_SITE_HEADER = 'Sunshine Portal Admin Page'
    ADMIN_SITE_TITLE = 'Sunshine-Portal-Production'
    ADMIN_SITE_INDEX_TITLE = 'PRODUCTION instance of Sunshine Portal. Please be careful to change anything here.'

# ------------------------------------------------------------------------------
# Upload and static files settings
# ------------------------------------------------------------------------------
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # higher than the count of fields
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')
MEDIA_URL = '/cdn/direct/'
